# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioStreamingHeaders' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioStreamingHeaders
  pod 'FreeStreamer', :git => 'https://github.com/muhku/FreeStreamer.git', :branch => 'master'

  target 'AudioStreamingHeaders-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioStreamingHeadersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AudioStreamingHeaders-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
